export const navContent = {
  en: {
    home: "Home",
    about: "About Us",
    project: "The Project",
    timeline: "Timeline & Updates",
    schedule: "Engagement Schedule",
    team: "Our Team",
    gallery: "Gallery",
    getInvolved: "Get Involved",
    careers: "Join Us",
    hiringBadge: "We're Hiring",
    language: "EN",
    languageFull: "English",
  },
  fr: {
    home: "Accueil",
    about: "À Propos",
    project: "Le Projet",
    timeline: "Chronologie et Mises à Jour",
    schedule: "Calendrier d'Engagement",
    team: "Notre Équipe",
    gallery: "Galerie",
    getInvolved: "S'Impliquer",
    careers: "Rejoindre",
    hiringBadge: "Nous Recrutons",
    language: "FR",
    languageFull: "Français",
  }
};
