export const en = {
  title: "Preliminary Data - Survey Results Report",
  characteristicsTitle: "Our Data",
  censusComparisonTitle: "Statistics Canada Data",
  chartLabel: "Percentage (%)",
  cities: {
    burnaby: "Burnaby",
    courtenay: "Courtenay",
    total: "Total",
  },
  burnaby: {
    lastUpdated: "Last updated: 18-02-2026",
    keyInsightsLabel: "Key Insights:",
    keyInsights:
      "Arab, Japanese, and West Asian groups are overrepresented, while South Asian, Southeast Asian, and Filipino groups are underrepresented.",
    censusEthnicities: [
      { name: "Arab", percentage: 1.03 },
      { name: "Black", percentage: 2.03 },
      { name: "Chinese", percentage: 33.29 },
      { name: "Filipino", percentage: 5.82 },
      { name: "Japanese", percentage: 1.53 },
      { name: "Korean", percentage: 3.80 },
      { name: "Latin American", percentage: 2.50 },
      { name: "Multiple visible minorities", percentage: 2.60 },
      { name: "Not a visible minority", percentage: 32.16 },
      { name: "South Asian", percentage: 9.42 },
      { name: "Southeast Asian", percentage: 2.55 },
      { name: "Visible minority, n.i.e.", percentage: 0.64 },
      { name: "West Asian", percentage: 2.62 },
    ],
    ethnicities: [
      { name: "Arab", percentage: 13.76 },
      { name: "Black", percentage: 1.59 },
      { name: "Chinese", percentage: 32.80 },
      { name: "Filipino", percentage: 2.65 },
      { name: "Indigenous peoples", percentage: 2.12 },
      { name: "Japanese", percentage: 2.12 },
      { name: "Korean", percentage: 3.70 },
      { name: "Latin American", percentage: 3.70 },
      { name: "Not a visible minority", percentage: 20.63 },
      {
        name: "South Asian",
        percentage: 7.41,
      },
      {
        name: "Southeast Asian",
        percentage: 2.12,
      },
      { name: "West Asian", percentage: 4.76 },
      { name: "Prefer not to disclose", percentage: 2.65 },
    ],
  },
  courtenay: {
    lastUpdated: "Last updated: 18-02-2026",
    keyInsightsLabel: "Key Insights:",
    keyInsights:
      "Overrepresentation of immigrants and racialized groups across all ethnicities.",
    censusEthnicities: [
      { name: "Arab", percentage: 0.22 },
      { name: "Black", percentage: 0.83 },
      { name: "Chinese", percentage: 1.44 },
      { name: "Filipino", percentage: 1.51 },
      { name: "Japanese", percentage: 0.31 },
      { name: "Korean", percentage: 0.54 },
      { name: "Latin American", percentage: 0.41 },
      { name: "Multiple visible minorities", percentage: 0.23 },
      { name: "Not a visible minority", percentage: 91.66 },
      { name: "South Asian", percentage: 1.60 },
      { name: "Southeast Asian", percentage: 0.95 },
      { name: "Visible minority, n.i.e.", percentage: 0.18 },
      { name: "West Asian", percentage: 0.13 },
    ],
    ethnicities: [
      { name: "Arab", percentage: 0.83 },
      { name: "Black", percentage: 3.33 },
      { name: "Chinese", percentage: 8.33 },
      { name: "Filipino", percentage: 2.50 },
      { name: "Indigenous peoples", percentage: 2.50 },
      { name: "Japanese", percentage: 1.67 },
      { name: "Korean", percentage: 2.50 },
      { name: "Latin American", percentage: 3.33 },
      { name: "Not a visible minority", percentage: 63.33 },
      { name: "Prefer not to disclose", percentage: 3.33 },
      {
        name: "South Asian",
        percentage: 4.17,
      },
      {
        name: "Southeast Asian",
        percentage: 3.33,
      },
      { name: "West Asian", percentage: 0.83 },
    ],
  },
};

export type SurveyDataReportType = typeof en;

export const fr: SurveyDataReportType = {
  title: "Données Préliminaires - Rapport des Résultats du Sondage",
  characteristicsTitle: "Nos Données",
  censusComparisonTitle: "Données Statistique Canada",
  chartLabel: "Pourcentage (%)",
  cities: {
    burnaby: "Burnaby",
    courtenay: "Courtenay",
    total: "Total",
  },
  burnaby: {
    lastUpdated: "Dernière mise à jour: 18-02-2026",
    keyInsightsLabel: "Aperçus Clés:",
    keyInsights:
          "Les groupes arabes, japonais et asiatiques de l'Ouest sont surreprésentés, tandis que les groupes sud-asiatiques, asiatiques du Sud-Est et philippins sont sous-représentés.",
        censusEthnicities: [
          { name: "Arabe", percentage: 1.03 },
          { name: "Noir", percentage: 2.03 },
          { name: "Chinois", percentage: 33.29 },
          { name: "Philippin", percentage: 5.82 },
          { name: "Japonais", percentage: 1.53 },
          { name: "Coréen", percentage: 3.80 },
          { name: "Latino-Américain", percentage: 2.50 },
          { name: "Minorités visibles multiples", percentage: 2.60 },
          { name: "Pas une minorité visible", percentage: 32.16 },
          { name: "Sud-Asiatique", percentage: 9.42 },
          { name: "Asiatique du Sud-Est", percentage: 2.55 },
          { name: "Minorité visible, n.i.a.", percentage: 0.64 },
          { name: "Asie de l'Ouest", percentage: 2.62 },
        ],
        ethnicities: [
          { name: "Arabe", percentage: 13.76 },
          { name: "Noir", percentage: 1.59 },
          { name: "Chinois", percentage: 32.80 },
          { name: "Philippin", percentage: 2.65 },
          { name: "Peuples autochtones", percentage: 2.12 },
          { name: "Japonais", percentage: 2.12 },
          { name: "Coréen", percentage: 3.70 },
          { name: "Latino-Américain", percentage: 3.70 },
          { name: "Pas une minorité visible", percentage: 20.63 },
          {
            name: "Sud-Asiatique",
            percentage: 7.41,
          },
          {
            name: "Asiatique du Sud-Est",
            percentage: 2.12,
          },
          {
            name: "Asie de l'Ouest",
            percentage: 4.76,
          },
          { name: "Préfère ne pas divulguer", percentage: 2.65 },
        ],
      },
      courtenay: {
        lastUpdated: "Dernière mise à jour: 18-02-2026",
        keyInsightsLabel: "Aperçus Clés:",
        keyInsights:
          "Surreprésentation des immigrants et des groupes racialisés dans toutes les catégories ethniques.",
        censusEthnicities: [
          { name: "Arabe", percentage: 0.22 },
          { name: "Noir", percentage: 0.83 },
          { name: "Chinois", percentage: 1.44 },
          { name: "Philippin", percentage: 1.51 },
          { name: "Japonais", percentage: 0.31 },
          { name: "Coréen", percentage: 0.54 },
          { name: "Latino-Américain", percentage: 0.41 },
          { name: "Minorités visibles multiples", percentage: 0.23 },
          { name: "Pas une minorité visible", percentage: 91.66 },
          { name: "Sud-Asiatique", percentage: 1.60 },
          { name: "Asiatique du Sud-Est", percentage: 0.95 },
          { name: "Minorité visible, n.i.a.", percentage: 0.18 },
          { name: "Asie de l'Ouest", percentage: 0.13 },
        ],
        ethnicities: [
          { name: "Arabe", percentage: 0.83 },
          { name: "Noir", percentage: 3.33 },
          { name: "Chinois", percentage: 8.33 },
          { name: "Philippin", percentage: 2.50 },
          { name: "Peuples autochtones", percentage: 2.50 },
          { name: "Japonais", percentage: 1.67 },
          { name: "Coréen", percentage: 2.50 },
          { name: "Latino-Américain", percentage: 3.33 },
          { name: "Pas une minorité visible", percentage: 63.33 },
          {
            name: "Sud-Asiatique",
            percentage: 4.17,
          },
          {
            name: "Asiatique du Sud-Est",
            percentage: 3.33,
          },
          {
            name: "Asie de l'Ouest",
            percentage: 0.83,
          },
          { name: "Préfère ne pas divulguer", percentage: 3.33 },
        ],
      },
};