// --- Shared percentage data (language-independent) ---

const BurnabyCensusEthnicities = {
  Arab: 1.03,
  Black: 2.03,
  Chinese: 33.29,
  Filipino: 5.82,
  Japanese: 1.53,
  Korean: 3.80,
  LatinAmerican: 2.50,
  MultipleVisibleMinorities: 2.60,
  NotAVisibleMinority: 32.16,
  SouthAsian: 9.42,
  SoutheastAsian: 2.55,
  VisibleMinorityNIE: 0.64,
  WestAsian: 2.62,
};

const BurnabyEthnicities = {
  Arab: 13.20,
  Black: 1.52,
  Chinese: 32.49,
  Filipino: 3.05,
  IndigenousPeoples: 2.03,
  Japanese: 2.54,
  Korean: 4.06,
  LatinAmerican: 3.55,
  NotAVisibleMinority: 20.30, 
  SouthAsian: 8.12,
  SoutheastAsian: 2.03,
  WestAsian: 4.57,
  PreferNotToDisclose: 2.54,
};

const CourtenayCensusEthnicities = {
  Arab: 0.22,
  Black: 0.83,
  Chinese: 1.44,
  Filipino: 1.51,
  Japanese: 0.31,
  Korean: 0.54,
  LatinAmerican: 0.41,
  MultipleVisibleMinorities: 0.23,
  NotAVisibleMinority: 91.66,
  SouthAsian: 1.60,
  SoutheastAsian: 0.95,
  VisibleMinorityNIE: 0.18,
  WestAsian: 0.13,
};

const CourtenayEthnicities = {
  Arab: 0.80,
  Black: 3.20,
  Chinese: 8.80,
  Filipino: 2.40,
  IndigenousPeoples: 2.40,
  Japanese: 1.60,
  Korean: 2.40,
  LatinAmerican: 3.20,
  NotAVisibleMinority: 61.60, 
  PreferNotToDisclose: 3.20,
  SouthAsian: 4.80,
  SoutheastAsian: 4.00,
  WestAsian: 1.60,
};

const TotalEthnicities = {
  Arab: 8.39,
  Black: 2.17,
  Chinese: 23.29,
  Filipino: 2.80,
  IndigenousPeoples: 2.17,
  Japanese: 2.17,
  Korean: 3.42,
  LatinAmerican: 3.42,
  NotAVisibleMinority: 36.34, 
  PreferNotToDisclose: 2.80,
  SouthAsian: 6.83,
  SoutheastAsian: 2.80,
  WestAsian: 3.42,
};

// --- Language-specific content ---

export const en = {
  title: "Preliminary Data - Survey Results Report",
  characteristicsTitle: "Our Data",
  censusComparisonTitle: "Statistics Canada Data",
  ethnicBackgroundCensusTitle: "Ethnic Background from Statistics Canada Data",
  ethnicBackgroundOurDataTitle: "Ethnic Background from Our Data",
  chartLabel: "Percentage (%)",
  cities: {
    burnaby: "Burnaby",
    courtenay: "Courtenay",
    total: "Total",
  },
  burnaby: {
    lastUpdated: "Last updated: 18-02-2026",
    keyInsightsLabel: "Key Insights:",
    keyInsights:
      "Arab, Japanese, and West Asian groups are overrepresented, while South Asian, Southeast Asian, and Filipino groups are underrepresented.",
    censusEthnicities: [
      { name: "Arab",                       percentage: BurnabyCensusEthnicities.Arab },
      { name: "Black",                      percentage: BurnabyCensusEthnicities.Black },
      { name: "Chinese",                    percentage: BurnabyCensusEthnicities.Chinese },
      { name: "Filipino",                   percentage: BurnabyCensusEthnicities.Filipino },
      { name: "Japanese",                   percentage: BurnabyCensusEthnicities.Japanese },
      { name: "Korean",                     percentage: BurnabyCensusEthnicities.Korean },
      { name: "Latin American",             percentage: BurnabyCensusEthnicities.LatinAmerican },
      { name: "Multiple visible minorities",percentage: BurnabyCensusEthnicities.MultipleVisibleMinorities },
      { name: "Not a visible minority",     percentage: BurnabyCensusEthnicities.NotAVisibleMinority },
      { name: "South Asian",                percentage: BurnabyCensusEthnicities.SouthAsian },
      { name: "Southeast Asian",            percentage: BurnabyCensusEthnicities.SoutheastAsian },
      { name: "Visible minority, n.i.e.",   percentage: BurnabyCensusEthnicities.VisibleMinorityNIE },
      { name: "West Asian",                 percentage: BurnabyCensusEthnicities.WestAsian },
    ],
    ethnicities: [
      { name: "Arab",                   percentage: BurnabyEthnicities.Arab },
      { name: "Black",                  percentage: BurnabyEthnicities.Black },
      { name: "Chinese",                percentage: BurnabyEthnicities.Chinese },
      { name: "Filipino",               percentage: BurnabyEthnicities.Filipino },
      { name: "Indigenous peoples",     percentage: BurnabyEthnicities.IndigenousPeoples },
      { name: "Japanese",               percentage: BurnabyEthnicities.Japanese },
      { name: "Korean",                 percentage: BurnabyEthnicities.Korean },
      { name: "Latin American",         percentage: BurnabyEthnicities.LatinAmerican },
      { name: "Not a visible minority", percentage: BurnabyEthnicities.NotAVisibleMinority },
      { name: "South Asian",            percentage: BurnabyEthnicities.SouthAsian },
      { name: "Southeast Asian",        percentage: BurnabyEthnicities.SoutheastAsian },
      { name: "West Asian",             percentage: BurnabyEthnicities.WestAsian },
      { name: "Prefer not to disclose", percentage: BurnabyEthnicities.PreferNotToDisclose },
    ],
  },
  courtenay: {
    lastUpdated: "Last updated: 18-02-2026",
    keyInsightsLabel: "Key Insights:",
    keyInsights:
      "Overrepresentation of immigrants and racialized groups across all ethnicities.",
    censusEthnicities: [
      { name: "Arab",                       percentage: CourtenayCensusEthnicities.Arab },
      { name: "Black",                      percentage: CourtenayCensusEthnicities.Black },
      { name: "Chinese",                    percentage: CourtenayCensusEthnicities.Chinese },
      { name: "Filipino",                   percentage: CourtenayCensusEthnicities.Filipino },
      { name: "Japanese",                   percentage: CourtenayCensusEthnicities.Japanese },
      { name: "Korean",                     percentage: CourtenayCensusEthnicities.Korean },
      { name: "Latin American",             percentage: CourtenayCensusEthnicities.LatinAmerican },
      { name: "Multiple visible minorities",percentage: CourtenayCensusEthnicities.MultipleVisibleMinorities },
      { name: "Not a visible minority",     percentage: CourtenayCensusEthnicities.NotAVisibleMinority },
      { name: "South Asian",                percentage: CourtenayCensusEthnicities.SouthAsian },
      { name: "Southeast Asian",            percentage: CourtenayCensusEthnicities.SoutheastAsian },
      { name: "Visible minority, n.i.e.",   percentage: CourtenayCensusEthnicities.VisibleMinorityNIE },
      { name: "West Asian",                 percentage: CourtenayCensusEthnicities.WestAsian },
    ],
    ethnicities: [
      { name: "Arab",                   percentage: CourtenayEthnicities.Arab },
      { name: "Black",                  percentage: CourtenayEthnicities.Black },
      { name: "Chinese",                percentage: CourtenayEthnicities.Chinese },
      { name: "Filipino",               percentage: CourtenayEthnicities.Filipino },
      { name: "Indigenous peoples",     percentage: CourtenayEthnicities.IndigenousPeoples },
      { name: "Japanese",               percentage: CourtenayEthnicities.Japanese },
      { name: "Korean",                 percentage: CourtenayEthnicities.Korean },
      { name: "Latin American",         percentage: CourtenayEthnicities.LatinAmerican },
      { name: "Not a visible minority", percentage: CourtenayEthnicities.NotAVisibleMinority },
      { name: "Prefer not to disclose", percentage: CourtenayEthnicities.PreferNotToDisclose },
      { name: "South Asian",            percentage: CourtenayEthnicities.SouthAsian },
      { name: "Southeast Asian",        percentage: CourtenayEthnicities.SoutheastAsian },
      { name: "West Asian",             percentage: CourtenayEthnicities.WestAsian },
    ],
  },
  total: {
    lastUpdated: "Last updated: 18-02-2026",
    keyInsightsLabel: "Key Insights:",
    keyInsights: "",
    censusEthnicities: [],
    ethnicities: [
      { name: "Arab",                   percentage: TotalEthnicities.Arab },
      { name: "Black",                  percentage: TotalEthnicities.Black },
      { name: "Chinese",                percentage: TotalEthnicities.Chinese },
      { name: "Filipino",               percentage: TotalEthnicities.Filipino },
      { name: "Indigenous peoples",     percentage: TotalEthnicities.IndigenousPeoples },
      { name: "Japanese",               percentage: TotalEthnicities.Japanese },
      { name: "Korean",                 percentage: TotalEthnicities.Korean },
      { name: "Latin American",         percentage: TotalEthnicities.LatinAmerican },
      { name: "Not a visible minority", percentage: TotalEthnicities.NotAVisibleMinority },
      { name: "Prefer not to disclose", percentage: TotalEthnicities.PreferNotToDisclose },
      { name: "South Asian",            percentage: TotalEthnicities.SouthAsian },
      { name: "Southeast Asian",        percentage: TotalEthnicities.SoutheastAsian },
      { name: "West Asian",             percentage: TotalEthnicities.WestAsian },
    ],
  },
};

export type SurveyDataReportType = typeof en;

export const fr: SurveyDataReportType = {
  title: "Données Préliminaires - Rapport des Résultats du Sondage",
  characteristicsTitle: "Nos Données",
  censusComparisonTitle: "Données Statistique Canada",
  ethnicBackgroundCensusTitle: "Origine ethnique selon Statistique Canada",
  ethnicBackgroundOurDataTitle: "Origine ethnique selon nos données",
  chartLabel: "Pourcentage (%)",
  cities: {
    burnaby: "Burnaby",
    courtenay: "Courtenay",
    total: "Total",
  },
  burnaby: {
    lastUpdated: "Dernière mise à jour: 18-02-2026",
    keyInsightsLabel: "Aperçus Clés:",
    keyInsights:
      "Les groupes arabes, japonais et asiatiques de l'Ouest sont surreprésentés, tandis que les groupes sud-asiatiques, asiatiques du Sud-Est et philippins sont sous-représentés.",
    censusEthnicities: [
      { name: "Arabe",                        percentage: BurnabyCensusEthnicities.Arab },
      { name: "Noir",                         percentage: BurnabyCensusEthnicities.Black },
      { name: "Chinois",                      percentage: BurnabyCensusEthnicities.Chinese },
      { name: "Philippin",                    percentage: BurnabyCensusEthnicities.Filipino },
      { name: "Japonais",                     percentage: BurnabyCensusEthnicities.Japanese },
      { name: "Coréen",                       percentage: BurnabyCensusEthnicities.Korean },
      { name: "Latino-Américain",             percentage: BurnabyCensusEthnicities.LatinAmerican },
      { name: "Minorités visibles multiples", percentage: BurnabyCensusEthnicities.MultipleVisibleMinorities },
      { name: "Pas une minorité visible",     percentage: BurnabyCensusEthnicities.NotAVisibleMinority },
      { name: "Sud-Asiatique",                percentage: BurnabyCensusEthnicities.SouthAsian },
      { name: "Asiatique du Sud-Est",         percentage: BurnabyCensusEthnicities.SoutheastAsian },
      { name: "Minorité visible, n.i.a.",     percentage: BurnabyCensusEthnicities.VisibleMinorityNIE },
      { name: "Asie de l'Ouest",              percentage: BurnabyCensusEthnicities.WestAsian },
    ],
    ethnicities: [
      { name: "Arabe",                    percentage: BurnabyEthnicities.Arab },
      { name: "Noir",                     percentage: BurnabyEthnicities.Black },
      { name: "Chinois",                  percentage: BurnabyEthnicities.Chinese },
      { name: "Philippin",                percentage: BurnabyEthnicities.Filipino },
      { name: "Peuples autochtones",      percentage: BurnabyEthnicities.IndigenousPeoples },
      { name: "Japonais",                 percentage: BurnabyEthnicities.Japanese },
      { name: "Coréen",                   percentage: BurnabyEthnicities.Korean },
      { name: "Latino-Américain",         percentage: BurnabyEthnicities.LatinAmerican },
      { name: "Pas une minorité visible", percentage: BurnabyEthnicities.NotAVisibleMinority },
      { name: "Sud-Asiatique",            percentage: BurnabyEthnicities.SouthAsian },
      { name: "Asiatique du Sud-Est",     percentage: BurnabyEthnicities.SoutheastAsian },
      { name: "Asie de l'Ouest",          percentage: BurnabyEthnicities.WestAsian },
      { name: "Préfère ne pas divulguer", percentage: BurnabyEthnicities.PreferNotToDisclose },
    ],
  },
  courtenay: {
    lastUpdated: "Dernière mise à jour: 18-02-2026",
    keyInsightsLabel: "Aperçus Clés:",
    keyInsights:
      "Surreprésentation des immigrants et des groupes racialisés dans toutes les catégories ethniques.",
    censusEthnicities: [
      { name: "Arabe",                        percentage: CourtenayCensusEthnicities.Arab },
      { name: "Noir",                         percentage: CourtenayCensusEthnicities.Black },
      { name: "Chinois",                      percentage: CourtenayCensusEthnicities.Chinese },
      { name: "Philippin",                    percentage: CourtenayCensusEthnicities.Filipino },
      { name: "Japonais",                     percentage: CourtenayCensusEthnicities.Japanese },
      { name: "Coréen",                       percentage: CourtenayCensusEthnicities.Korean },
      { name: "Latino-Américain",             percentage: CourtenayCensusEthnicities.LatinAmerican },
      { name: "Minorités visibles multiples", percentage: CourtenayCensusEthnicities.MultipleVisibleMinorities },
      { name: "Pas une minorité visible",     percentage: CourtenayCensusEthnicities.NotAVisibleMinority },
      { name: "Sud-Asiatique",                percentage: CourtenayCensusEthnicities.SouthAsian },
      { name: "Asiatique du Sud-Est",         percentage: CourtenayCensusEthnicities.SoutheastAsian },
      { name: "Minorité visible, n.i.a.",     percentage: CourtenayCensusEthnicities.VisibleMinorityNIE },
      { name: "Asie de l'Ouest",              percentage: CourtenayCensusEthnicities.WestAsian },
    ],
    ethnicities: [
      { name: "Arabe",                    percentage: CourtenayEthnicities.Arab },
      { name: "Noir",                     percentage: CourtenayEthnicities.Black },
      { name: "Chinois",                  percentage: CourtenayEthnicities.Chinese },
      { name: "Philippin",                percentage: CourtenayEthnicities.Filipino },
      { name: "Peuples autochtones",      percentage: CourtenayEthnicities.IndigenousPeoples },
      { name: "Japonais",                 percentage: CourtenayEthnicities.Japanese },
      { name: "Coréen",                   percentage: CourtenayEthnicities.Korean },
      { name: "Latino-Américain",         percentage: CourtenayEthnicities.LatinAmerican },
      { name: "Pas une minorité visible", percentage: CourtenayEthnicities.NotAVisibleMinority },
      { name: "Préfère ne pas divulguer", percentage: CourtenayEthnicities.PreferNotToDisclose },
      { name: "Sud-Asiatique",            percentage: CourtenayEthnicities.SouthAsian },
      { name: "Asiatique du Sud-Est",     percentage: CourtenayEthnicities.SoutheastAsian },
      { name: "Asie de l'Ouest",          percentage: CourtenayEthnicities.WestAsian },
    ],
  },
  total: {
    lastUpdated: "Dernière mise à jour: 18-02-2026",
    keyInsightsLabel: "Aperçus Clés:",
    keyInsights: "",
    censusEthnicities: [],
    ethnicities: [
      { name: "Arabe",                    percentage: TotalEthnicities.Arab },
      { name: "Noir",                     percentage: TotalEthnicities.Black },
      { name: "Chinois",                  percentage: TotalEthnicities.Chinese },
      { name: "Philippin",                percentage: TotalEthnicities.Filipino },
      { name: "Peuples autochtones",      percentage: TotalEthnicities.IndigenousPeoples },
      { name: "Japonais",                 percentage: TotalEthnicities.Japanese },
      { name: "Coréen",                   percentage: TotalEthnicities.Korean },
      { name: "Latino-Américain",         percentage: TotalEthnicities.LatinAmerican },
      { name: "Pas une minorité visible", percentage: TotalEthnicities.NotAVisibleMinority },
      { name: "Préfère ne pas divulguer", percentage: TotalEthnicities.PreferNotToDisclose },
      { name: "Sud-Asiatique",            percentage: TotalEthnicities.SouthAsian },
      { name: "Asiatique du Sud-Est",     percentage: TotalEthnicities.SoutheastAsian },
      { name: "Asie de l'Ouest",          percentage: TotalEthnicities.WestAsian },
    ],
  },
};